# example toml
[experiment]
name = "evaluation_test_1_more_epochs"
description = "evaluation_test_1_more_epochs"

[data]
data_dir = "/root/Mu3eProject/RawData/TransformerData/TrainingDataT2/signal1_97/"
test_file = "signal1_97_sorted_test.pt"
test_helperfile = "signal1_97_test_helper.pt"
test_truthfile = "signal1_97_test_truths_shuffled.csv"
dataloader_num_workers = 4
num_classes = 5400


[model]
checkpoint_path = "/root/Mu3eProject/RawData/TransformerData/results/run_20250303_174631/model_final.pth"
inputfeature_dim = 3
num_heads = 8
embed_dim = 128
num_layers = 6
dropout = 0.1


[training]
batch_size = 32


[output]
base_path = "/root/Mu3eProject/RawData/TransformerData/results/run_20250303_174631/eval"



[logging]
level = "INFO"

[wandb]
project_name = "Transformer_tracking"
run_name = "signal1_97_evaluation_test_3"
